name: IContas CI - PR para Main (Heroku)

on:
  pull_request:
      branches:
        - main

jobs:
  build-deploy-heroku:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurando Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build da aplicação com application-test
      run: mvn -B clean package -Ptest
    - name: Deploy para o Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email:  ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP}}name: IContas CI - PR para Main (Heroku)

on:
  pull_request:
      branches:
        - main

jobs:
  build-deploy-heroku:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurando Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build da aplicação com application-test
      run: mvn -B clean package -Ptest
    - name: Deploy para o Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email:  ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP}}name: IContas CI - PR para Main (Heroku)

on:
  pull_request:
      branches:
        - main

jobs:
  build-deploy-heroku:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurando Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build da aplicação com application-test
      run: mvn -B clean package -Ptest
    - name: Deploy para o Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email:  ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP}}